[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "ipykernel>=6.29.5",
    "tiktoken>=0.9.0",
    "transformers>=4.49.0",
]
